---
- name: execute cowsay
  ansible.builtin.command: cowsay "{{ str }}"
  register: cowsay_result
  become: yes

- name: install nginx
  ansible.builtin.apt:
    name: nginx
    state: latest
  become: yes

- name: copy nginx config file
  ansible.builtin.template:
    src: ../files/nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: reload nginx
  become: yes

- name: copy index.html file
  ansible.builtin.template:
    src: ../files/index.html.j2
    dest: "{{root_dir}}/index.html"
  become: yes

