- hosts: webservers
  remote_user: root

  vars:
    nginx_port: 8080
    root_dir: /usr/share/nginx/html
    hostname: "{{ ansible_facts['hostname'] }}"
    str: "This is server {{ hostname }}"

  tasks:
#    - name: Print all available facts
#      ansible.builtin.debug:
#        var: ansible_facts
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
      become: yes

    - name: copy nginx config file
      ansible.builtin.template:
        src: ../files/nginx.conf
        dest: /etc/nginx/nginx.conf
      notify: reload nginx
      become: yes

    - name: copy index.html file
      ansible.builtin.template:
        src: ../files/index.html
        dest: "{{root_dir}}/index.html"
      become: yes

  handlers:
    - name: reload nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes
