- hosts: webservers
  remote_user: root
  gather_facts: no
  vars:
    users:
      - name: bamie
      - name: bansa
      - name: bobert


  tasks:
    - name: update apt cache
      ansible.builtin.apt:
        update_cache: yes
      become: yes

    - name: install git
      ansible.builtin.apt:
        name: git
        state: present
      become: yes

    - name: create user
      ansible.builtin.user:
        name: "{{ item.name }}"
        state: present
      loop: "{{ users }}"
      become: yes
      tags: [user]

    - name: create git config
      ansible.builtin.template:
        src: ../files/gitconfig
        dest: /home/{{ item.name }}/.gitconfig
      loop: "{{ users }}"

    - name: create ssh directory
      ansible.builtin.file:
         path: /home/{{ item.name }}/.ssh
         state: directory
         mode: 0755
      loop: "{{ users }}"

    - name: add ssh key
      ansible.builtin.copy:
        src: ../files/id_rsa
        dest: /home/{{ item.name }}/.ssh/authorized_keys
        mode: 0644
      loop: "{{ users }}"
