- hosts: webservers
  remote_user: root
  vars:
    users:
      - name: bamie
      - name: bansa
      - name: bobert


  tasks:
      - name: delete user
        ansible.builtin.user:
          name: "{{ item.name }}"
          state: absent
        become: yes
        loop: "{{ users }}"
        tags: [delete-user]